#!/bin/bash

if [ "$1" = "--debug" ]; then
  echo "Running perl6 script in debug mode..."
  EXEC=perl6-gdb-m
  shift
elif [ "$1" = "--valgrind" ]; then
  echo "Running perl6 script in valgrind mode..."
  EXEC=perl6-valgrind-m
  shift
elif [ "$1" = "--pbuild" ]; then
  PARALLEL_BUILD=1
  EXEC=perl6
  shift
else
  #echo "Running perl6 script..."
  EXEC=perl6
fi

INCLUDES="\
-I${P6_X11_HOME}/Method-Also/lib  \
-Ilib -Ibin"

# Handle any extra directories in project file.
MOREI=`grep libdir .x11-project | \
cut -d= -f 2 | \
perl6 -ne '.say for .lines.split(",")'`
for a in $MOREI; do INCLUDES="-I$a $INCLUDES"; done

if [[ -z "${PARALLEL_BUILD}" ]]; then
  ${EXEC} --stagestats ${EXTRAS} ${INCLUDES} "$@"
else
  ${EXEC} --stagestats ${EXTRAS} ${INCLUDES} "$@" 2>&1 | perl -pe 's/^/$$ /'
fi
